// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiESgg-AFvErYv9uCA0sMCXA-HWCCBya8',
    appId: '1:885100442553:web:7f6295f0830a15cabebc68',
    messagingSenderId: '885100442553',
    projectId: 'tiktok-devgony',
    authDomain: 'tiktok-devgony.firebaseapp.com',
    storageBucket: 'tiktok-devgony.appspot.com',
    measurementId: 'G-TT5LG327MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyZACnYxqA1OhQqP6wej8oXa9tySjAhk',
    appId: '1:885100442553:android:e4410c0c204bbf2fbebc68',
    messagingSenderId: '885100442553',
    projectId: 'tiktok-devgony',
    storageBucket: 'tiktok-devgony.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx1WQwL6yPtrqt3HLNE0k9ZQzI8Y9lzBg',
    appId: '1:885100442553:ios:ad5fcc2577afb218bebc68',
    messagingSenderId: '885100442553',
    projectId: 'tiktok-devgony',
    storageBucket: 'tiktok-devgony.appspot.com',
    iosClientId: '885100442553-a6hk70eg76b92sho3k6u3p54l71a8kvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokCloneHenry',
  );
}
